<a href="https://colab.research.google.com/github/Hardikr23/tensorflow_codes/blob/main/fmnist_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

fmnist_data = keras.datasets.fashion_mnist

In [ ]:
(x_train, y_train),(x_test, y_test) = fmnist_data.load_data()

In [ ]:
type(x_train)
x_train.shape

(60000, 28, 28)

In [ ]:
np.set_printoptions(linewidth=320)
print(x_train[1,:])
print(y_train[1])

[[  0   0   0   0   0   1   0   0   0   0  41 188 103  54  48  43  87 168 133  16   0   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0  49 136 219 216 228 236 255 255 255 255 217 215 254 231 160  45   0   0   0   0   0]
 [  0   0   0   0   0  14 176 222 224 212 203 198 196 200 215 204 202 201 201 201 209 218 224 164   0   0   0   0]
 [  0   0   0   0   0 188 219 200 198 202 198 199 199 201 196 198 198 200 200 200 200 201 200 225  41   0   0   0]
 [  0   0   0   0  51 219 199 203 203 212 238 248 250 245 249 246 247 252 248 235 207 203 203 222 140   0   0   0]
 [  0   0   0   0 116 226 206 204 207 204 101  75  47  73  48  50  45  51  63 113 222 202 206 220 224   0   0   0]
 [  0   0   0   0 200 222 209 203 215 200   0  70  98   0 103  59  68  71  49   0 219 206 214 210 250  38   0   0]
 [  0   0   0   0 247 218 212 210 215 214   0 254 243 139 255 174 251 255 205   0 215 217 214 208 220  95   0   0]
 [  0   0   0  45 226 214 214 215 224 205   0  42  35  60  16  17  12  13  70   

In [ ]:
# Normalizing the data
x_train = x_train/255
x_test = x_test/255

In [ ]:
print(x_train[1,:])

[[0.         0.         0.         0.         0.         0.00392157 0.         0.         0.         0.         0.16078431 0.7372549  0.40392157 0.21176471 0.18823529 0.16862745 0.34117647 0.65882353 0.52156863 0.0627451  0.         0.         0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.00392157 0.         0.         0.         0.19215686 0.53333333 0.85882353 0.84705882 0.89411765 0.9254902  1.         1.         1.         1.         0.85098039 0.84313725 0.99607843 0.90588235 0.62745098 0.17647059 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.05490196 0.69019608 0.87058824 0.87843137 0.83137255 0.79607843 0.77647059 0.76862745 0.78431373 0.84313725 0.8        0.79215686 0.78823529 0.78823529 0.78823529 0.81960784 0.85490196 0.87843137 0.64313725 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.7372549 

In [ ]:
inputs = np.array([[1.0, 3.0, 4.0, 2.0]])
inputs = tf.convert_to_tensor(inputs)
print(f'input to softmax function: {inputs.numpy()}')

# Feed the inputs to a softmax activation function
outputs = tf.keras.activations.softmax(inputs)
print(f'output of softmax function: {outputs.numpy()}')

# Get the sum of all values after the softmax
sum = tf.reduce_sum(outputs)
print(f'sum of outputs: {sum}')


input to softmax function: [[1. 3. 4. 2.]]
output of softmax function: [[0.0320586  0.23688282 0.64391426 0.08714432]]
sum of outputs: 1.0


In [ ]:
class my_call_back(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if (logs.get('accuracy') > 0.85):
      print("85% Acc reached. Stopping training\n")
      self.model.stop_training = True

# class myCallback(tf.keras.callbacks.Callback):
#   def on_epoch_end(self, epoch, logs={}):
#     if(logs.get('accuracy') >= 0.6): # Experiment with changing this value
#       print("\nReached 60% accuracy so cancelling training!")
#       self.model.stop_training = True

In [ ]:
from tensorflow.python.ops.gen_nn_ops import softmax
callbacks = my_call_back()
model = keras.Sequential([keras.layers.Flatten(), \
                         keras.layers.Dense(units=128, activation=tf.nn.relu), \
                         keras.layers.Dense(units=10, activation=tf.nn.softmax),\
                         ])
model.compile(optimizer=tf.optimizers.Adam(),
              loss="sparse_categorical_crossentropy", 
              metrics=["accuracy"])

In [ ]:
model.fit(x_train, y_train, epochs=5, callbacks=[callbacks])

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4973 - accuracy: 0.8265
Epoch 2/5
1866/1875 [============================>.] - ETA: 0s - loss: 0.3766 - accuracy: 0.864185% Acc reached. Stopping training

1875/1875 [==============================] - 5s 3ms/step - loss: 0.3769 - accuracy: 0.8640


In [ ]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.3986 - accuracy: 0.8565


[0.398647665977478, 0.8565000295639038]

In [ ]:
classifications = model.predict(x_test)


In [ ]:
print(classifications[0])

[9.5885072e-05 1.4776947e-07 9.8746250e-06 4.3953487e-06 2.3874578e-05 8.6870134e-02 1.6087610e-05 7.7895865e-02 2.0165544e-03 8.3306718e-01]


In [ ]:
print(y_test[0])

9
