<a href="https://colab.research.google.com/github/Hardikr23/tensorflow_codes/blob/main/mnist_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
mnist_data = keras.datasets.mnist
(x_train, y_train),(x_test, y_test) = mnist_data.load_data()

In [ ]:
np.set_printoptions(linewidth=320)
print(x_train[1,:])
print(y_train[1])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  51 159 253 159  50   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0  48 238 252 252 252 237   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  54 227 253 252 239 233 252  57   6   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  10  60 224 252 253 252 202  84 252 253 122   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0 163 252 252 252 253 252 252  96 18

In [ ]:
x_train = x_train/255
x_test = x_test/255

In [ ]:
print(x_train[1,:])

[[0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        

In [ ]:
inputs = np.array([[1.0, 3.0, 4.0, 2.0]])
inputs = tf.convert_to_tensor(inputs)
print(f'input to sigmoid function: {inputs.numpy()}')

# Feed the inputs to a sigmoid activation function
outputs = tf.keras.activations.sigmoid(inputs)
print(f'output of sigmoid function: {outputs.numpy()}')

# Get the sum of all values after the sigmoid
sum = tf.reduce_sum(outputs)
print(f'sum of outputs: {sum}')

input to sigmoid function: [[1. 3. 4. 2.]]
output of sigmoid function: [[0.73105858 0.95257413 0.98201379 0.88079708]]
sum of outputs: 3.5464435734682294


In [ ]:
model = keras.Sequential([
                          keras.layers.Flatten(),
                          keras.layers.Dense(128, activation=tf.nn.relu),
                          keras.layers.Dense(10, activation=tf.nn.softmax)
])

In [ ]:
model.compile(optimizer=tf.optimizers.Adam(), loss='sparse_categorical_crossentropy', metrics=["accuracy"])

In [ ]:
class my_call_back(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epochs, logs={}):
    if(logs.get("accuracy") > 0.98):
      print("\n80% Acc reached. Stopping Training\n")
      self.model.stop_training = True

In [ ]:
callback = my_call_back()
model.fit(x_train, y_train, epochs=5, callbacks=[callback])

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2577 - accuracy: 0.9267
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1120 - accuracy: 0.9668
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0755 - accuracy: 0.9769
Epoch 4/5
1873/1875 [============================>.] - ETA: 0s - loss: 0.0574 - accuracy: 0.9829
80% Acc reached. Stopping Training

1875/1875 [==============================] - 5s 3ms/step - loss: 0.0574 - accuracy: 0.9829


In [ ]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 4ms/step - loss: 0.0830 - accuracy: 0.9749


[0.08298369497060776, 0.9749000072479248]